extends Node

const AUDIO_DOOR_OPEN = preload("res://assets/sound/bathroom shower door open 1.wav")
const AUDIO_DOOR_CLOSE = preload("res://assets/sound/bathroom shower door close 1.wav")
const AUDIO_PICK_DICTIONARY = preload("res://assets/sound/paper picked up 5.wav")
const AUDIO_LAMP = preload("res://assets/sound/button assorted 40.wav")
const AUDIO_MOUSE_PICK = preload("res://assets/sound/freesound_community-mice-sqeak-26522.mp3")
const AUDIO_MOUSE = preload("res://assets/sound/freesound_community-cartoon-mouse-96437.mp3")
const AUDIO_OSCILLO = preload("res://assets/sound/freesound_community-electronic-buzzing-sound-29464.mp3")
const AUDIO_OSCILLO_BEEP_1 = preload("res://assets/sound/eaglaxle-electronic-beep-1-453381.mp3")
const AUDIO_OSCILLO_BEEP_2 = preload("res://assets/sound/eaglaxle-electronic-beep-2-453382.mp3")
const AUDIO_OSCILLO_BEEP_3 = preload("res://assets/sound/eaglaxle-electronic-beep-3-453383.mp3")
const AUDIO_OSCILLO_BEEP_4 = preload("res://assets/sound/eaglaxle-electronic-beep-4-453387.mp3")
const AUDIO_OSCILLO_WIN = preload("res://assets/sound/freesound_community-electronic-hit-98242.mp3")
const AUDIO_SUTOM_TYPING = preload("res://assets/sound/virtualzero-keyboard-typing-solo-371229.mp3")
const AUDIO_SUTOM_VALIDATE = preload("res://assets/sound/confirmation_002.ogg")
const AUDIO_SUTOM_ERROR = preload("res://assets/sound/error_005.ogg")
const AUDIO_TYPING_SOLO = preload("res://assets/sound/virtualzero-keyboard-typing-solo-371229.mp3")
const AUDIO_CABLE = preload("res://assets/sound/pluck_001.ogg")
const AUDIO_CABLE_VALIDATE = preload("res://assets/sound/confirmation_001.ogg")
const AUDIO_CABLE_VALIDATE_ALL = preload("res://assets/sound/confirmation_002.ogg")
const AUDIO_CABLE_ERROR = preload("res://assets/sound/error_002.ogg")
const AUDIO_TV_ON = preload("res://assets/sound/colto-enable-device-133456.mp3")
const AUDIO_TV_SELECT = preload("res://assets/sound/select_002.ogg")
const AUDIO_TV_VALIDATE = preload("res://assets/sound/confirmation_002.ogg")
const AUDIO_TV_ERROR = preload("res://assets/sound/error_003.ogg")
